name: CI-UnitTests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
            pip install django==3.2
            pip install dj-database-url
      - name: Run tests
        run: python -m runtests